-- to get good query plans based on the size of the actual data,
-- need to run these after uploading data...

ANALYZE TABLE SRC_CD COMPUTE STATISTICS;
ANALYZE TABLE DERIV_CD COMPUTE STATISTICS;
ANALYZE TABLE DATA_SRC COMPUTE STATISTICS;
ANALYZE TABLE FOOTNOTE COMPUTE STATISTICS;
ANALYZE TABLE LANGDESC COMPUTE STATISTICS;
ANALYZE TABLE NUTR_DEF COMPUTE STATISTICS;
ANALYZE TABLE FD_GROUP COMPUTE STATISTICS;
ANALYZE TABLE FOOD_DES COMPUTE STATISTICS;
ANALYZE TABLE NUT_DATA COMPUTE STATISTICS;
ANALYZE TABLE WEIGHT COMPUTE STATISTICS;
ANALYZE TABLE LANGUAL COMPUTE STATISTICS;
ANALYZE TABLE DATSRCLN COMPUTE STATISTICS;

ANALYZE INDEX DATSRCLN_NUT_IX COMPUTE STATISTICS;
ANALYZE INDEX DATSRCLN_SRC_IX COMPUTE STATISTICS;
ANALYZE INDEX LANGUAL_FAC_IX COMPUTE STATISTICS;
ANALYZE INDEX NUT_DATA_NUTDEF_IX COMPUTE STATISTICS;
ANALYZE INDEX FOOD_DES_IX COMPUTE STATISTICS;

EXIT;